name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "API/Drinks API with Newman/Drinks - Testing Collection.postman_collection.json" -e API/Drinks API with Newman/DrinksEnv.postman_environment.json
